services:
  app:
    image: bloglist-frontend
    volumes:
      - ./frontend/:/usr/src/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      # I didn't get this to work otherwise: not a good idea, but this is just
      # a demo!

  server:
    image: bloglist-backend
    volumes:
      - ./backend/:/app
    build:
      context: ./backend
      dockerfile: Dockerfile

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server